name: Publish to AWS

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run Tests and Build Assembly
      run: sbt test assembly
    - name: AWS Update Lambda Action
      uses: stcalica/update-lambda@359ca7975ee5cc5c389fc84b0e11532e39f7b707
      with:
        package: "./target/scala-3.1.3/scala3-aws-lambda-dynamodb-importer-assembly-0.1.0.jar"
        function-name: "scala3-aws-lambda-dynamodb-importer"
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_REGION: "us-east-1"
