#https://www.stevenskelton.ca/scala-sbt-publishing-to-github-packages/

name: Publish Über Assembly to Github Packages

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Publish Über Jar to Github Packages
        run: sbt publishAssemblyToGithubPackages
